lex_dict = {
    'en': [
        { 'word': '1_True_55.png', 'wstatus': 0, 'dummy': 1 }, // 隧
        { 'word': 'denial', 'wstatus': 1, 'dummy': 1 },
        { 'word': 'generic', 'wstatus': 1, 'dummy': 1 },
        { 'word': 'mensible', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'scornful', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'stoutly', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'ablaze', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'kermshaw', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'moonlit', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'lofty', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'hurricane', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'flaw', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'alberation', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'unkempt', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'breeding', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'festivity', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'screech', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'savoury', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'plaudate', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'shin', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'fluid', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'spaunch', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'allied', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'slain', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'recipient', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'exprate', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'eloquence', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'cleanliness', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'dispatch', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'rebondicate', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'ingenious', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'bewitch', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'skave', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'plaintively', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'kilp', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'interfate', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'hasty', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'lengthy', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'fray', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'crumper', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'upkeep', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'majestic', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'magrity', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'nourishment', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'abergy', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'proom', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'turmoil', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'carbohydrate', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'scholar', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'turtle', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'fellick', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'destription', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'cylinder', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'censorship', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'celestial', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'rascal', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'purrage', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'pulsh', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'muddy', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'quirty', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'pudour', 'wstatus': 0, 'dummy': 0 },
        { 'word': 'listless', 'wstatus': 1, 'dummy': 0 },
        { 'word': 'wrought', 'wstatus': 1, 'dummy': 0 }
    ],
    'ch': [
        { 'filename': '1_True_55.png', 'valid': 1 },
        { 'filename': '2_Wrong_2.png', 'valid': 0 },
        { 'filename': '3_True_29.png', 'valid': 1 },
        { 'filename': '4_Wrong_22.png', 'valid': 0 },
        { 'filename': '5_True_50.png', 'valid': 1 },
        { 'filename': '6_True_2.png', 'valid': 1 },
        { 'filename': '7_Wrong_15.png', 'valid': 0 },
        { 'filename': '8_True_48.png', 'valid': 1 },
        { 'filename': '9_True_23.png', 'valid': 1 },
        { 'filename': '10_True_1.png', 'valid': 1 },
        { 'filename': '11_Wrong_7.png', 'valid': 0 },
        { 'filename': '12_Wrong_4.png', 'valid': 0 },
        { 'filename': '13_True_54.png', 'valid': 1 },
        { 'filename': '14_True_56.png', 'valid': 1 },
        { 'filename': '15_True_14.png', 'valid': 1 },
        { 'filename': '16_True_44.png', 'valid': 1 },
        { 'filename': '17_True_16.png', 'valid': 1 },
        { 'filename': '18_True_47.png', 'valid': 1 },
        { 'filename': '19_Wrong_12.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem107.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem115.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem017.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem102.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem168.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem004.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem139.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem175.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem043.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_nonceitem039.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem109.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem156.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem173.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem172.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem022.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem118.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem027.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem157.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem007.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem165.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem108.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem154.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem137.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem097.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem133.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem023.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem179.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem155.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem062.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem105.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem089.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_nonceitem024.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem144.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem143.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem044.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_nonceitem040.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem100.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem162.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem171.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem026.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem119.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem101.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem176.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem098.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem016.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_nonceitem013.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem153.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem147.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem068.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem177.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem140.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem112.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem114.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem161.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem029.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_nonceitem034.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem121.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem095.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem059.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem129.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem047.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem106.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem103.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem037.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem127.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem158.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem167.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem005.png', 'valid': 0 },
        { 'filename': 'LEXTALE_CH_lexitem130.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_lexitem138.png', 'valid': 1 },
        { 'filename': 'LEXTALE_CH_nonceitem042.png', 'valid': 0 }
    ]
};
